import React from "react";
import { CodeBlock } from "@/components/code-block";
import { cn } from "@/lib/utils";
import { previews } from "@/autogenerated/previews";

type PreviewsKeys = keyof typeof previews;

export interface ComponentCodeProps {
  name: PreviewsKeys;
  className?: string;
  defaultExpanded?: boolean;
  preview?: string;
  expandable?: boolean;
  language?: string;
  example?: boolean;
}

export const ComponentCode = ({
  name,
  className,
  preview,
  expandable,
  language,
  example
}: ComponentCodeProps): JSX.Element => {
  // make it server component
 
  const code = React.useMemo(() => {
    const allCodeFiles = previews[name]?.code ?? [];

    if (allCodeFiles.length === 0) {
      return [];
    }

    return allCodeFiles.map((file) => ({
      ...file,
      code: file.code.replace("export default function", "function"),
    }));
  }, [name]);

  return (
    <div
      className={cn(
        "mt-2 overflow-hidden rounded-md space-y-4",
        className
      )}
    >
      <CodeBlock
        files={code.map((file) => ({
          fileName: file.title,
          code: file.code,
          lang: "tsx",
        }))}
        preview={preview}
        className={"w-full rounded-t-none border-x-0 border-b-0"}
        expandable={expandable}
        language={language}
        example={example}
      />
    </div>
  );
};
