
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  "nav": [
    {
      "title": "Getting Started",
      "slug": "docs",
      "items": [
        {
          "title": "Installation",
          "href": "/docs/installation"
        }
      ]
    },
    {
      "title": "Components",
      "slug": "components",
      "items": [
        {
          "title": "Angular",
          "href": "/components/angular",
          "items": [
            {
              "title": "Button",
              "href": "/components/angular/button"
            }
          ]
        },
        {
          "title": "React",
          "href": "/components/react",
          "items": [
            {
              "title": "Alert dialog",
              "href": "/components/react/alert-dialog"
            },
            {
              "title": "Alert",
              "href": "/components/react/alert"
            },
            {
              "title": "Aspect ratio",
              "href": "/components/react/aspect-ratio"
            },
            {
              "title": "Avatar",
              "href": "/components/react/avatar"
            },
            {
              "title": "Badge",
              "href": "/components/react/badge"
            },
            {
              "title": "Breadcrumbs",
              "href": "/components/react/breadcrumbs"
            },
            {
              "title": "Button",
              "href": "/components/react/button"
            },
            {
              "title": "Card",
              "href": "/components/react/card"
            },
            {
              "title": "Checkbox",
              "href": "/components/react/checkbox"
            },
            {
              "title": "Collapsible",
              "href": "/components/react/collapsible"
            },
            {
              "title": "Combobox",
              "href": "/components/react/combobox"
            },
            {
              "title": "Command",
              "href": "/components/react/command"
            },
            {
              "title": "Dialog",
              "href": "/components/react/dialog"
            },
            {
              "title": "Divider",
              "href": "/components/react/divider"
            },
            {
              "title": "Drawer",
              "href": "/components/react/drawer"
            },
            {
              "title": "Dropdown",
              "href": "/components/react/dropdown"
            },
            {
              "title": "Form",
              "href": "/components/react/form"
            },
            {
              "title": "Hover card",
              "href": "/components/react/hover-card"
            },
            {
              "title": "Label",
              "href": "/components/react/label"
            },
            {
              "title": "Marquee",
              "href": "/components/react/marquee"
            },
            {
              "title": "Multi select",
              "href": "/components/react/multi-select"
            },
            {
              "title": "Pagination",
              "href": "/components/react/pagination"
            },
            {
              "title": "Popover",
              "href": "/components/react/popover"
            },
            {
              "title": "Radio group",
              "href": "/components/react/radio-group"
            },
            {
              "title": "Resizable",
              "href": "/components/react/resizable"
            },
            {
              "title": "Scroll area",
              "href": "/components/react/scroll-area"
            },
            {
              "title": "Select",
              "href": "/components/react/select"
            },
            {
              "title": "Separator",
              "href": "/components/react/separator"
            },
            {
              "title": "Sheet",
              "href": "/components/react/sheet"
            },
            {
              "title": "Skeleton",
              "href": "/components/react/skeleton"
            },
            {
              "title": "Slider",
              "href": "/components/react/slider"
            },
            {
              "title": "Star rating",
              "href": "/components/react/star-rating"
            },
            {
              "title": "Stepper",
              "href": "/components/react/stepper"
            },
            {
              "title": "Switch",
              "href": "/components/react/switch"
            },
            {
              "title": "Table",
              "href": "/components/react/table"
            },
            {
              "title": "Tabs",
              "href": "/components/react/tabs"
            },
            {
              "title": "Text field",
              "href": "/components/react/text-field"
            },
            {
              "title": "Textarea",
              "href": "/components/react/textarea"
            },
            {
              "title": "Timeline",
              "href": "/components/react/timeline"
            },
            {
              "title": "Toast",
              "href": "/components/react/toast"
            },
            {
              "title": "Toc",
              "href": "/components/react/toc"
            },
            {
              "title": "Toggle",
              "href": "/components/react/toggle"
            },
            {
              "title": "Tooltip",
              "href": "/components/react/tooltip"
            },
            {
              "title": "Tree",
              "href": "/components/react/tree"
            }
          ]
        },
        {
          "title": "Vue",
          "href": "/components/vue",
          "items": [
            {
              "title": "Button",
              "href": "/components/vue/button"
            }
          ]
        }
      ]
    }
  ]
};
