
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  "nav": [
    {
      "title": "Getting Started",
      "slug": "docs",
      "items": [
        {
          "title": "Installation",
          "href": "/docs/installation"
        }
      ]
    },
    {
      "title": "Components",
      "slug": "components",
      "items": [
        {
          "title": "React",
          "href": "/components/react",
          "items": [
            {
              "title": "Buttons",
              "href": "/components/react/buttons",
              "items": [
                {
                  "title": "Button",
                  "href": "/components/react/buttons/button"
                },
                {
                  "title": "Star rating",
                  "href": "/components/react/buttons/star-rating"
                },
                {
                  "title": "Toggle",
                  "href": "/components/react/buttons/toggle"
                }
              ]
            },
            {
              "title": "Data-display",
              "href": "/components/react/data-display",
              "items": [
                {
                  "title": "Alert",
                  "href": "/components/react/data-display/alert"
                },
                {
                  "title": "Avatar",
                  "href": "/components/react/data-display/avatar"
                },
                {
                  "title": "Badge",
                  "href": "/components/react/data-display/badge"
                },
                {
                  "title": "Card",
                  "href": "/components/react/data-display/card"
                },
                {
                  "title": "Collapsible",
                  "href": "/components/react/data-display/collapsible"
                },
                {
                  "title": "Divider",
                  "href": "/components/react/data-display/divider"
                },
                {
                  "title": "Separator",
                  "href": "/components/react/data-display/separator"
                },
                {
                  "title": "Table",
                  "href": "/components/react/data-display/table"
                },
                {
                  "title": "Timeline",
                  "href": "/components/react/data-display/timeline"
                }
              ]
            },
            {
              "title": "Draggable",
              "href": "/components/react/draggable",
              "items": [
                {
                  "title": "Resizable",
                  "href": "/components/react/draggable/resizable"
                }
              ]
            },
            {
              "title": "Feedback",
              "href": "/components/react/feedback",
              "items": [
                {
                  "title": "Skeleton",
                  "href": "/components/react/feedback/skeleton"
                },
                {
                  "title": "Slider",
                  "href": "/components/react/feedback/slider"
                }
              ]
            },
            {
              "title": "Form",
              "href": "/components/react/form",
              "items": [
                {
                  "title": "Form",
                  "href": "/components/react/form/form"
                }
              ]
            },
            {
              "title": "Input",
              "href": "/components/react/input",
              "items": [
                {
                  "title": "Checkbox",
                  "href": "/components/react/input/checkbox"
                },
                {
                  "title": "Label",
                  "href": "/components/react/input/label"
                },
                {
                  "title": "Multi select",
                  "href": "/components/react/input/multi-select"
                },
                {
                  "title": "Radio group",
                  "href": "/components/react/input/radio-group"
                },
                {
                  "title": "Select",
                  "href": "/components/react/input/select"
                },
                {
                  "title": "Switch",
                  "href": "/components/react/input/switch"
                },
                {
                  "title": "Text field",
                  "href": "/components/react/input/text-field"
                },
                {
                  "title": "Textarea",
                  "href": "/components/react/input/textarea"
                }
              ]
            },
            {
              "title": "Layout",
              "href": "/components/react/layout",
              "items": [
                {
                  "title": "Aspect ratio",
                  "href": "/components/react/layout/aspect-ratio"
                },
                {
                  "title": "Scroll area",
                  "href": "/components/react/layout/scroll-area"
                }
              ]
            },
            {
              "title": "Navigation",
              "href": "/components/react/navigation",
              "items": [
                {
                  "title": "Breadcrumbs",
                  "href": "/components/react/navigation/breadcrumbs"
                },
                {
                  "title": "Pagination",
                  "href": "/components/react/navigation/pagination"
                },
                {
                  "title": "Stepper",
                  "href": "/components/react/navigation/stepper"
                },
                {
                  "title": "Tabs",
                  "href": "/components/react/navigation/tabs"
                }
              ]
            },
            {
              "title": "Overlay",
              "href": "/components/react/overlay",
              "items": [
                {
                  "title": "Alert dialog",
                  "href": "/components/react/overlay/alert-dialog"
                },
                {
                  "title": "Command",
                  "href": "/components/react/overlay/command"
                },
                {
                  "title": "Dialog",
                  "href": "/components/react/overlay/dialog"
                },
                {
                  "title": "Drawer",
                  "href": "/components/react/overlay/drawer"
                },
                {
                  "title": "Popover",
                  "href": "/components/react/overlay/popover"
                },
                {
                  "title": "Sheet",
                  "href": "/components/react/overlay/sheet"
                },
                {
                  "title": "Toast",
                  "href": "/components/react/overlay/toast"
                },
                {
                  "title": "Tooltip",
                  "href": "/components/react/overlay/tooltip"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
