
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  "nav": [
    {
      "title": "Getting Started",
      "slug": "docs",
      "items": [
        {
          "title": "Installation",
          "href": "/docs/installation"
        }
      ]
    },
    {
      "title": "Components",
      "slug": "components",
      "items": [
        {
          "title": "Angular",
          "href": "/components/angular",
          "items": [
            {
              "title": "Buttons",
              "href": "/components/angular/buttons",
              "items": [
                {
                  "title": "Button",
                  "href": "/components/angular/buttons/button"
                }
              ]
            }
          ]
        },
        {
          "title": "React",
          "href": "/components/react",
          "items": [
            {
              "title": "Buttons",
              "href": "/components/react/buttons",
              "items": [
                {
                  "title": "Button",
                  "href": "/components/react/buttons/button"
                },
                {
                  "title": "Star rating",
                  "href": "/components/react/buttons/star-rating"
                },
                {
                  "title": "Toggle",
                  "href": "/components/react/buttons/toggle"
                }
              ]
            },
            {
              "title": "Data-display",
              "href": "/components/react/data-display",
              "items": [
                {
                  "title": "Avatar",
                  "href": "/components/react/data-display/avatar"
                },
                {
                  "title": "Badge",
                  "href": "/components/react/data-display/badge"
                },
                {
                  "title": "Card",
                  "href": "/components/react/data-display/card"
                },
                {
                  "title": "Divider",
                  "href": "/components/react/data-display/divider"
                },
                {
                  "title": "Separator",
                  "href": "/components/react/data-display/separator"
                },
                {
                  "title": "Table",
                  "href": "/components/react/data-display/table"
                }
              ]
            },
            {
              "title": "Draggable",
              "href": "/components/react/draggable",
              "items": [
                {
                  "title": "Resizable",
                  "href": "/components/react/draggable/resizable"
                }
              ]
            },
            {
              "title": "Feedback",
              "href": "/components/react/feedback",
              "items": [
                {
                  "title": "Skeleton",
                  "href": "/components/react/feedback/skeleton"
                },
                {
                  "title": "Slider",
                  "href": "/components/react/feedback/slider"
                }
              ]
            },
            {
              "title": "Form",
              "href": "/components/react/form",
              "items": [
                {
                  "title": "Form",
                  "href": "/components/react/form/form"
                }
              ]
            },
            {
              "title": "Input",
              "href": "/components/react/input",
              "items": [
                {
                  "title": "Label",
                  "href": "/components/react/input/label"
                },
                {
                  "title": "Multi select",
                  "href": "/components/react/input/multi-select"
                }
              ]
            },
            {
              "title": "Layout",
              "href": "/components/react/layout",
              "items": [
                {
                  "title": "Aspect ratio",
                  "href": "/components/react/layout/aspect-ratio"
                },
                {
                  "title": "Scroll area",
                  "href": "/components/react/layout/scroll-area"
                }
              ]
            },
            {
              "title": "Navigation",
              "href": "/components/react/navigation",
              "items": [
                {
                  "title": "Breadcrumbs",
                  "href": "/components/react/navigation/breadcrumbs"
                }
              ]
            }
          ]
        },
        {
          "title": "Vue",
          "href": "/components/vue",
          "items": [
            {
              "title": "Buttons",
              "href": "/components/vue/buttons",
              "items": [
                {
                  "title": "Button",
                  "href": "/components/vue/buttons/button"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
